### ISSUE TITLE
Probleme mit Umlauten auf RPi und Android

### ISSUE THREAD

**Issue by p4f456** [stereodruid/plugin.video.osmosis#1]
Kann weiterhin keine Serien mit Umlauten im Titel hinzufügen, weder mit 0.2.4 noch mit 0.3.0
http://pastebin.com/7VEUPhMs

**Comment by stereodruid** [comment]
Danke ich kümmere mich darum.

**Comment by stereodruid** [comment]
Solved with 0.3.1
