### ISSUE TITLE
Fehler bei Addon "Youtube Music"  

### ISSUE THREAD

**Issue by usman2006** [stereodruid/plugin.video.osmosis#2]
bekomme Fehler beim hin fügen von Listen,
bsp
Billboard --> Hot 100

01:02:38.766 T:1546646432   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: sequence item 0: expected string, NoneType found
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.osmosis/default.py", line 194, in <module>
                                                fileSys.writeMediaList(url, name, cType)
                                              File "/storage/.kodi/addons/plugin.video.osmosis/modules/fileSys.py", line 114, in writeMediaList
                                                theentry = '|'.join([cType, name.decode("utf-8"), url]) + '\n'
                                            TypeError: sequence item 0: expected string, NoneType found
                                            -->End of Python script error report<--
01:03:25.591 T:1395651488 WARNING: Attempt to use invalid handle -1
01:03:29.670 T:1395651488 WARNING: Previous line repeats 4 times.
01:03:29.671 T:1395651488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: sequence item 0: expected string, NoneType found
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.osmosis/default.py", line 194, in <module>
                                                fileSys.writeMediaList(url, name, cType)
                                              File "/storage/.kodi/addons/plugin.video.osmosis/modules/fileSys.py", line 114, in writeMediaList
                                                theentry = '|'.join([cType, name.decode("utf-8"), url]) + '\n'
                                            TypeError: sequence item 0: expected string, NoneType found
                                            -->End of Python script error report<--
01:05:10.158 T:1351611296 WARNING: Attempt to use invalid handle -1
01:05:14.772 T:1351611296 WARNING: Previous line repeats 4 times.
01:05:14.772 T:1351611296   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: sequence item 0: expected string, NoneType found
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.osmosis/default.py", line 194, in <module>
                                                fileSys.writeMediaList(url, name, cType)
                                              File "/storage/.kodi/addons/plugin.video.osmosis/modules/fileSys.py", line 114, in writeMediaList
                                                theentry = '|'.join([cType, name.decode("utf-8"), url]) + '\n'
                                            TypeError: sequence item 0: expected string, NoneType found
                                            -->End of Python script error report<--
01:05:19.374 T:1960912672   ERROR: GetDirectory - Error getting plugin://plugin.video.osmosis/?fanart=image%3A%2F%2F%252Fstorage%252F.kodi%252Faddons%252Fplugin.video.spotitube%252Ffanart.jpg%2F&mode=101&name=Youtube%20Music&url=plugin%3A%2F%2Fplugin.video.spotitube
01:05:19.376 T:1960912672   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.osmosis/?fanart=image%3A%2F%2F%252Fstorage%252F.kodi%252Faddons%252Fplugin.video.spotitube%252Ffanart.jpg%2F&mode=101&name=Youtube%20Music&url=plugin%3A%2F%2Fplugin.video.spotitube) failed
01:05:27.311 T:1311765408   ERROR: GetDirectory - Error getting
01:05:58.826 T:1960912672   ERROR: Previous line repeats 2 times.
01:05:58.826 T:1960912672   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
01:06:01.765 T:1395651488 WARNING: Attempt to use invalid handle 389
01:06:06.355 T:1395651488 WARNING: Attempt to use invalid handle -1
01:07:17.090 T:1340076960 WARNING: Previous line repeats 4 times.
01:07:17.090 T:1340076960   ERROR: Unable to find plugin
01:07:17.090 T:1960912672   ERROR: GetDirectory - Error getting plugin://
01:07:17.092 T:1960912672   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
01:07:17.895 T:1419731872   ERROR: GetDirectory - Error getting
01:08:15.955 T:1311765408   ERROR: Previous line repeats 2 times.

**Comment by stereodruid** [comment]
Werde es mir mal anschauen.

**Comment by stereodruid** [comment]
Kannat du es bitte noch mal mit der RC1 Version, aus dem Kodinerds-Thread testen!

**Comment by usman2006** [comment]
leider bekomme ich immer noch einen fehler


21:37:46.123 T:1423598496 WARNING: Previous line repeats 9 times.
21:37:46.124 T:1423598496   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: sequence item 0: expected string, NoneType found
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.osmosis/default.py", line 194, in <module>
                                                fileSys.writeMediaList(url, name, cType)
                                              File "/storage/.kodi/addons/plugin.video.osmosis/modules/fileSys.py", line 114, in writeMediaList
                                                theentry = '|'.join([cType, name.decode("utf-8"), url]) + '\n'
                                            TypeError: sequence item 0: expected string, NoneType found
                                            -->End of Python script error report<--

**Comment by stereodruid** [comment]
Ok, es geht voran, scheint ein anderer Fehler zu sein.
Wie fügst du die Musik hinzu? Per "Video Addon" oder "Audio Addon"?

**Comment by usman2006** [comment]
video addon

**Comment by usman2006** [comment]
bekomme diesen Fehler mit 0.3.5 RC ver.


23:44:46.136 T:1961593808   ERROR: Previous line repeats 9 times.
23:44:46.136 T:1961593808   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
23:44:57.557 T:1430254496 WARNING: Attempt to use invalid handle 45
23:48:04.262 T:1444934560 WARNING: Attempt to use invalid handle -1
23:48:11.920 T:1444934560 WARNING: Previous line repeats 4 times.
23:48:11.920 T:1444934560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'path' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.osmosis/default.py", line 221, in <module>
                                                create.fillPluginItems(url, strm=True, strm_name=name, strm_type=cType)
                                              File "/storage/.kodi/addons/plugin.video.osmosis/modules/create.py", line 205, in fillPluginItems
                                                utils.addon_log(str(path + ' ' + filename))
                                            UnboundLocalError: local variable 'path' referenced before assignment
                                            -->End of Python script error report<--

**Comment by stereodruid** [comment]
YouTube?

**Comment by usman2006** [comment]
http://forum.kodi.tv/showthread.php?tid=200391. 

dieses addon, Youtube Music

**Comment by stereodruid** [comment]
OK, sehe es mir mal an.

**Comment by stereodruid** [comment]
Denke das ich den Fehler gefunden habe. Fix kommt mit dem nächsten Update.

**Comment by stereodruid** [comment]
Fehler sollte behoben sein. Bitte noch mal testen. 
Installation über die KodinerdsRepo oder GitHub

**Comment by usman2006** [comment]
geht leider immer noch nicht.
osmosis vor update gelöscht, alle übrig gebliebene ordner manuell gelöscht und dann neuinstaliert und einmal  alles standard gesetzt.


ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'path' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.osmosis/default.py", line 221, in <module>
                                                create.fillPluginItems(url, strm=True, strm_name=name, strm_type=cType)
                                              File "/storage/.kodi/addons/plugin.video.osmosis/modules/create.py", line 214, in fillPluginItems
                                                fileSys.writeSTRM(stringUtils.cleanStrms((path.rstrip("."))), stringUtils.cleanStrms(filename.rstrip(".")) , link)
                                            UnboundLocalError: local variable 'path' referenced before assignment
                                            -->End of Python script error report<--

**Comment by stereodruid** [comment]
Wie ist dein Vorgehen, welche Kategorie nutzt Du, TV, TV-Show, Cinema usw, welche Sprche.
Geht es immer noch um Billboard --> Hot 100? Bei mir werden die, Billboard --> Hot 100 einwandfrei erzeugt.

**Comment by usman2006** [comment]
others dann (en)

**Comment by stereodruid** [comment]
OK, werde es noch mal testen.

**Comment by usman2006** [comment]
welche kategorie benützt du ?
andere frag wie kann ich youtube abo in hauptmenü einbinden, wie Serien ? "zu letzet hingefügt"

**Comment by stereodruid** [comment]
Momentan werden Kategorien nur für Filme unterstützt.

Ich nutze, "Audio Addon" > Album

**Comment by usman2006** [comment]
...die videos aus youtube werden hinfügen aber die werden nur als datei ableget, muss die dann über den Verzeiniss aufrufen.
möchte das die wie serien ofer film in hauptmenü haben, ich weis man die nicht scrappen. 
andere möglichkeit gibt es nicht?

**Comment by usman2006** [comment]
bei mir wird aber Youtube Music nicht in Audio Addons gelistet sondern in Video

**Comment by stereodruid** [comment]
Wenn es um Musik geht, musst du die Musik als o den Ordner Album als Musikvideos scrapen.

**Comment by stereodruid** [comment]
Wenn es um Musik geht, musst du die Musik also den Ordner Album als Musikvideos scrapen.

**Comment by stereodruid** [comment]
Wenn die Dateien angelegt werden, müssen sie, wenn Musik, trotzdem als Musikvideos gescrapt werden.

**Comment by usman2006** [comment]
leider kann ich immer noch die Liste nicht hin fügen
meine Vorgehensweise.
Osmosis--> Video Addon --> Youtube Music --> Billboard --> Kontexmenu auf "Hot 100" --> create strms.
 
nach einigen Sekunden taucht ein Fehler auf.

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'path' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.osmosis/default.py", line 223, in <module>
                                                create.fillPluginItems(url, strm=True, strm_name=name, strm_type=cType)
                                              File "/storage/.kodi/addons/plugin.video.osmosis/modules/create.py", line 210, in fillPluginItems
                                                fileSys.writeSTRM(stringUtils.cleanStrms((path.rstrip("."))), stringUtils.cleanStrms(filename.rstrip(".")) , link)
                                            UnboundLocalError: local variable 'path' referenced before assignment
                                            -->End of Python script error report<--

**Comment by stereodruid** [comment]
Ich arbeite im Moment an einer eigenen Kategorie für YouTube. Das wird aber noch ne Weile dauern. Um die Weihnachtszeit werde ich nicht mehr viel machen. Aber ich versuch noch das Problem zu beheben.

**Comment by stereodruid** [comment]
Hi,
ich bin gerade dabei die neue Kategorie YouTube zu erstellen.
Ich habe jedoch Probleme mit dem YouTube Music Addon. Ich kann so gut wie nichts abspielen mit dem Addon.

Mit den Addons, YouMusic  und YouTube, funktioniert alles super.
Kannst du noch Musikvideos abspielen, mit YouTube Music?

**Comment by usman2006** [comment]
also bei mir funktioniert nun alles :D


Am 07.01.2017 um 00:42 schrieb Jan <notifications@github.com<mailto:notifications@github.com>>:


Hi,
ich bin gerade dabei die neue Kategorie YouTube zu erstellen.
Ich habe jedoch Probleme mit dem YouTube Music Addon. Ich kann so gut wie nichts abspielen mit dem Addon.

Mit den Addons, YouMusic und YouTube, funktioniert alles super.
Kannst du noch Musikvideos abspielen, mit YouTube Music?

-
