### ISSUE TITLE
update plugin.video.osmosis 

### ISSUE THREAD

**Issue by alex83100** [stereodruid/plugin.video.osmosis#26]
Hello, the update to version 1.29 does not work, Installing from a blank kodi also (android and Windows

**Comment by stereodruid** [comment]
Do you have a log file?
@Maven85 ist das Problem bekannt?

**Comment by alex83100** [comment]
I made a copy from github and I don't have any error now.

**Comment by stereodruid** [comment]
Perfect. Thanks for your response.

**Comment by alex83100** [comment]
I take this opportunity, is it possible to use your plugin with sub folders?  Currently osmosis only managed only one level of directory.

**Comment by stereodruid** [comment]
Take a look at the "Pull request". There are some merge request from @gu3nter. This requests will solve your problem, i guess!? 
https://github.com/stereodruid/plugin.video.osmosis/pulls

**Comment by alex83100** [comment]
I did an update with the latest version and I still have the problem. osmosis doesn't scan not my subfolders

**Comment by stereodruid** [comment]
Wat do you mean by scan? Osmo does not scan your folders. Do yo mean sites in your vid addon or folders? If you mean folders, then you have to set up your Scraper to search in folder recursive.

**Comment by alex83100** [comment]
Yes, I use the recursive mode to scrape my movies in kodi. I use with osmosis an addon that displays me the content of a "cloud" where are stored my movies. I can add directory by directory to osmosis, it generates me the strm files of the directory but it is not able to enter the subdirectory.

**Comment by stereodruid** [comment]
Please can you make a tree structure that represents the structure in your cloud addon? Something like this:
SomeFolder
-SomeCategory
-- SomeMoviename
-- SomeMoviename2

**Comment by alex83100** [comment]
Yes, it's similar

Movies
-Category1
-- Year 1
-- Year 2
-- ...
-Category2
-- Year 1
-- Year 2
-- ...

I can not ask for the creation of strm from movies, I am obliged to add osmosis to all directories year and after that works
