### ISSUE TITLE
local variable 'path' referenced before assignment

### ISSUE THREAD

**Issue by ghost** [stereodruid/plugin.video.osmosis#3]
Ich lasse einfach mal nen Log-Eintrag hier :)
(v0.3.3, Kodi 17, Windows 10)

```
15:44:23 T:12180   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'path' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\....\AppData\Roaming\Kodi\addons\plugin.video.osmosis\default.py", line 196, in <module>
                                                create.fillPluginItems(url, strm=True, strm_name=name, strm_type=cType)
                                              File "C:\Users\\....\\AppData\Roaming\Kodi\addons\plugin.video.osmosis\modules\create.py", line 205, in fillPluginItems
                                                utils.addon_log(str(path + ' ' + filename))
                                            UnboundLocalError: local variable 'path' referenced before assignment
                                            -->End of Python script error report<--
```

**Comment by stereodruid** [comment]
Gucke ich mir an. Danke für das Logfile.

**Comment by stereodruid** [comment]
Denke das ich den Fehler gefunden habe. Fix kommt mit dem nächsten Update.

**Comment by stereodruid** [comment]
Fehler sollte behoben sein. Bitte noch mal testen. 
Installation über die KodinerdsRepo oder GitHub

**Comment by ghost** [comment]
```
18:37:18 T:8512   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'path' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\....\AppData\Roaming\Kodi\addons\plugin.video.osmosis\default.py", line 221, in <module>
                                                create.fillPluginItems(url, strm=True, strm_name=name, strm_type=cType)
                                              File "C:\Users\....\AppData\Roaming\Kodi\addons\plugin.video.osmosis\modules\create.py", line 214, in fillPluginItems
                                                fileSys.writeSTRM(stringUtils.cleanStrms((path.rstrip("."))), stringUtils.cleanStrms(filename.rstrip(".")) , link)
                                            UnboundLocalError: local variable 'path' referenced before assignment
                                            -->End of Python script error report<--
```

0.3.6

**Comment by stereodruid** [comment]
Ich dachte das ich die Zeile verschoben hab. Muss wohl noch mal ran.

**Comment by ghost** [comment]
Der Fehler tritt ja in **fillPluginItems** auf. Path wird nur gesetztn wenn:

- "TV(" in strm_type gefunden wird
- "TV-Shows'" in strm_type gefunden wird
- strm_type "Audio-Album", "Audio-Single" oder "Other" ist

Mein strm_type ist aber "Movies(de)" aka path wird nicht gesetzt ^^. Ich kenne dein Addon nicht. Aber das es sich ja um "movies" handelt habe ich folgende Zeile:

https://github.com/stereodruid/plugin.video.osmosis/blob/master/modules/create.py#L109

wie folgt ersetzt:

`if strm_type.find('Cinema') != -1 or strm_type.find('Movies') != -1:`

Jetzt funktioniert es vom Prinzip. In meinen Fall werden zwar nur 100-Einträge erzeugt. Der Ordner hat 50 Einträge auf Seite 1. Dnan Folgen zwar noch mehr Seiten aber es scheint so das nur Seite 1 und Seite 2 erfasst werden.

**Comment by stereodruid** [comment]
Jetzt hat's klicke gemacht:) werde es später anpassen. Du kannst in den OSMOSIS-Settings die Seitenanzahl wählen, neue Funktion in 0.3.6.

**Comment by ghost** [comment]
Oh ok. Wäre es denn nicht besser sowas zu machen wie:

- Anzahl der Seiten begrenzen (default aus)
- Anzahl der Seiten aus Kategorie Filme (nur Editierbar wenn begrenzen an ist)

In meinen Fall weiß icht nämlich wieviel Seiten es sind und auf 100 begrenzen wollte ich es auch nicht ^^

Btw. es gibt keine validierung ob ein Eintrag schon mal in der MediaList ist. Ich habe daher beim testen grade 2x den gleichen eingetragen :(

**Comment by stereodruid** [comment]
Ich habe eine Funktion in Arbeit die doppelte Einträge verhindert. Das begrenzen auf 100 Seiten ist eine Sicherheitsmaßnahme. Es gibt Kategorien die weit mehr als 1000 Seiten, mit jeweils um die 40 Filme beinhalten. Das kann zu einem Speicherüberlauf führen. Du kannst aber die Begrenzung selbs aufheben.

**Comment by stereodruid** [comment]
Funktioniert deine Anpassung, oder gibt es noch weitere Probleme?

**Comment by ghost** [comment]
Ja bei mir Funktioniert sie ohne Probleme. Ich habe dein Addon aber nicht weiter gerprüft und kann die folgen daher nicht einschätzen^^

**Comment by stereodruid** [comment]
Alles klar, danke.

**Comment by stereodruid** [comment]
Ist das Problem, für dich behoben? Ich schließe diesen issue dann.

**Comment by ghost** [comment]
Jop der Fehler ist weg habe nen neuern^^ (issue kommt)
