### ISSUE TITLE
Unterordner mit Osmosis

### ISSUE THREAD

**Issue by alex83100** [stereodruid/plugin.video.osmosis#32]
Hallo, ich benutze Osmosis mit cloudstream Plugin. Damit können Sie Filme auf ihrem uptobox Konto gespeichert sehen. Uptobox können Verzeichnisse und Unterverzeichnis erstellen classsment zu erleichtern. Osmosis erzeugt jetzt eine Ordnerebene ist es möglich, als Unterordner zu durchsuchen?

**Comment by stereodruid** [comment]
It is not possible right now. Maybe the function/Option, gu3nter has created will solve this issue. You have to wait for the new release.
Maybe it would be helpful if you create a use case so we can see  what you really mean.

**Comment by alex83100** [comment]
ok, thanks, but I have a problem to scrape your strm files.
Name of the film (year).mkv.strm problem
Name of the film (year).strm no problem
Can you please clean the file before create strm mkv and avi?

**Comment by alex83100** [comment]
ok, I have found your file stingUtil.py and add (u'mkv', u''), (u'avi', u'') at line 100 it's ok

**Comment by stereodruid** [comment]
So dose it work for you now?
