### ISSUE TITLE
xst....

### ISSUE THREAD

**Issue by usman2006** [stereodruid/plugin.video.osmosis#5]
versuche Kategorie von HDfilme hinzufügen leider taucht immer fehler

12:41:37.204 T:1459110816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'path' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.osmosis/default.py", line 221, in <module>
                                                create.fillPluginItems(url, strm=True, strm_name=name, strm_type=cType)
                                              File "/storage/.kodi/addons/plugin.video.osmosis/modules/create.py", line 214, in fillPluginItems
                                                fileSys.writeSTRM(stringUtils.cleanStrms((path.rstrip("."))), stringUtils.cleanStrms(filename.rstrip(".")) , link)
                                            UnboundLocalError: local variable 'path' referenced before assignment
                                            -->End of Python script error report<--
12:44:04.826 T:1326990240 WARNING: Attempt to use invalid handle -1
12:44:12.338 T:1350026144 WARNING: Previous line repeats 4 times.
12:44:12.338 T:1350026144  NOTICE: 	[xStream] -> hdfilme_tv: *---- Running xStream, version 3.1.0 ----*
12:44:12.340 T:1350026144  NOTICE: 	[xStream] -> hdfilme_tv: Python-Version: 2.7.12
12:44:12.342 T:1350026144  NOTICE: 	[xStream] -> hdfilme_tv: {'function': 'showEntries', 'sUrl': 'http://hdfilme.tv/movie-movies?order_f=id', 'site': 'hdfilme_tv', 'title': 'Neu hinzugef\xc3\xbcgt'}
12:44:12.343 T:1350026144  NOTICE: 	[xStream] -> hdfilme_tv: Call function 'showEntries' from 'hdfilme_tv'
12:44:24.938 T:1326990240   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xfc' in position 86: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.osmosis/default.py", line 221, in <module>
                                                create.fillPluginItems(url, strm=True, strm_name=name, strm_type=cType)
                                              File "/storage/.kodi/addons/plugin.video.osmosis/modules/create.py", line 110, in fillPluginItems
                                                movieList = addMovies(detail, strm_name, strm_type)
                                              File "/storage/.kodi/addons/plugin.video.osmosis/modules/create.py", line 278, in addMovies
                                                fileSys.writeSTRM(stringUtils.cleanStrms((i[0].rstrip("."))), stringUtils.cleanStrms(i[1].rstrip(".")) , i[2] + "|" + i[1])
                                              File "/storage/.kodi/addons/plugin.video.osmosis/modules/fileSys.py", line 78, in writeSTRM
                                                makeSTRM(path, file, url)
                                              File "/storage/.kodi/addons/plugin.video.osmosis/modules/fileSys.py", line 96, in makeSTRM
                                                fle = open(fullpath, "w")
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 86: ordinal not in range(128)
                                            -->End of Python script error report<--
12:44:37.390 T:1417167776  NOTICE: 	[xStream] -> hdfilme_tv: *---- Running xStream, version 3.1.0 ----*
12:44:37.390 T:1417167776  NOTICE: 	[xStream] -> hdfilme_tv: Python-Version: 2.7.12
12:44:37.391 T:1417167776  NOTICE: 	[xStream] -> hdfilme_tv: {'function': 'load', 'params': '0', 'site': 'hdfilme_tv', 'title': 'HDfilme'}
12:44:37.392 T:1417167776  NOTICE: 	[xStream] -> hdfilme_tv: Call function 'load' from 'hdfilme_tv'
12:44:37.912 T:1417167776  NOTICE: 	[xStream] -> hdfilme_tv: Load HDfilme
12:44:44.194 T:1417167776  NOTICE: 	[xStream] *---- Running xStream, version 3.1.0 ----*
12:44:44.195 T:1417167776  NOTICE: 	[xStream] Python-Version: 2.7.12
12:44:44.196 T:1417167776  NOTICE: 	[xStream] {}
12:44:44.468 T:1417167776  NOTICE: 	[xStream] profile folder: /storage/.kodi/userdata/addon_data/plugin.video.xstream/
12:44:44.468 T:1417167776  NOTICE: 	[xStream] root folder: /storage/.kodi/addons/plugin.video.xstream
12:44:44.469 T:1417167776  NOTICE: 	[xStream] default sites folder: /storage/.kodi/addons/plugin.video.xstream/sites
12:44:44.894 T:1318601632  NOTICE: 	[xStream] *---- Running xStream, version 3.1.0 ----*
12:44:44.895 T:1318601632  NOTICE: 	[xStream] Python-Version: 2.7.12
12:44:44.896 T:1318601632  NOTICE: 	[xStream] {'function': 'updateAll'}
12:44:45.112 T:1318601632  NOTICE: 	[xStream] xStream xStreamUpdate
12:44:45.415 T:1341637536  NOTICE: 	[xStream] *---- Running xStream, version 3.1.0 ----*
12:44:45.416 T:1341637536  NOTICE: 	[xStream] Python-Version: 2.7.12
12:44:45.416 T:1341637536  NOTICE: 	[xStream] {'function': 'clearCache'}
12:44:49.125 T:1318601632  NOTICE: 	[xStream] xStream urlResolverUpdate

**Comment by stereodruid** [comment]
Teste bitte mal diese Version aus dem Future Branch:
https://github.com/stereodruid/plugin.video.osmosis/blob/Future-RC1/plugin.video.osmosis.zip

**Comment by stereodruid** [comment]
Und?

**Comment by usman2006** [comment]
ja hat funktioniert aber es hat mehr Seiten hinfügt als eingestellt( hab nur eine Seite in Addon Einstellung)

**Comment by stereodruid** [comment]
Ok, guck ich mir an.
