### ISSUE TITLE
Any way to get global context menu?

### ISSUE THREAD

**Issue by oOflyeyesOo** [stereodruid/plugin.video.osmosis#50]
Just so we won't have to go into the addon everytime, say we we are viewing in another addon.

**Comment by stereodruid** [comment]
Due to the internal processes it isn't possible.
The effort needed to realize that would be not worth it. Sorry.

**Comment by oOflyeyesOo** [comment]
Thanks for the reply, was just curious. I remember awhile back that SALTS
had a global context menu to play within any addon.

**Comment by stereodruid** [comment]
Sure, there are some Addons that have this function. Maybe in future development we will consider about A global menu. 

Regards.
