### ISSUE TITLE
expected string, NoneType found

### ISSUE THREAD

**Issue by ghost** [stereodruid/plugin.video.osmosis#9]
```
23:55:06.178 T:7248   DEBUG: [plugin.video.osmosis-0.4.1]: writeMediaList
23:55:06.178 T:7248   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: sequence item 0: expected string, NoneType found
                                            Traceback (most recent call last):
                                              File "C:\Users\....\AppData\Roaming\Kodi\addons\plugin.video.osmosis\default.py", line 221, in <module>
                                                fileSys.writeMediaList(url, name, cType)
                                              File "C:\Users\....\AppData\Roaming\Kodi\addons\plugin.video.osmosis\modules\fileSys.py", line 124, in writeMediaList
                                                theentry = '|'.join([cType, name.decode("utf-8"), url]) + '\n'
                                            TypeError: sequence item 0: expected string, NoneType found
                                            -->End of Python script error report<--
```

Ich habe mal etwas debugging betrieben. Schuld ist wohl das `cType` zu dem Zeitpunkt `none` ist. 

Und das liegt an `getType `in _guiTools.py_. Dort sieht deine IF wie folgt aus.

```
if selectType and selectLang >= 0:
        return Types[selectType]+ lang[selectLang]
```

Nur was ist wenn man im SelectDialog 'Cinema' oder 'YouTube Video' auswähle? Korrekt selectType is '0' und `0 == False`. Aka wenn man den ersten Punkt auswählt, im ersten Dialog, kommt immer `none `zurück.

```
if selectType >= 0 and selectLang >= 0:
        return Types[selectType]+ lang[selectLang]
```

Fixt den Fehler beim mir.

**Comment by stereodruid** [comment]
Glaube ich stehe auf dem Schlauch.  Wenn du etwas auswärts, also youtube und en, dann ist die Bedingung >= 0, größer oder gleich null, doch erfüllt. 
Der Index startet bei null, allso sollte das funktionieren. Oder verstehe ich dich falsch?

**Comment by ghost** [comment]
https://github.com/stereodruid/plugin.video.osmosis/blob/master/modules/guiTools.py#L141

Denken wir uns mal den Teil mit `selectLang` weg (den der is ok) dann sieht der Code quasi so aus:

```
Types = ['Cinema', 'TV-Shows', 'Shows-Collection', 'YouTube Music', 'VTS-Movie structure','Other']
selectType = selectDialog(Types)
if selectType:
    return Types[selectType]
```
(die URL Abfrage habe ich auch raus genommen damit der Code kürzer ist)

Die Rückgabe basiert ja auf Zahlen. Sprich 'Cinema' = 0, 'TV-Shows' = 1 usw. wählt der User garnichts aus kommt ein -1 zurück. Du fragst aber nur `if selectType: `ab. Das prüft ja nur ob selectType nicht `none` ist und das er nicht `False` ist.

Wählt man nun also 'Cinema' aus. Ist `selectType = 0`. Und wenn du mal versuchst einen Zahl in bool umzuwandeln ist `0` immer `False`. Wenn du einen anderen Eintrag auswählt ist die Zahl ja 1 und größer und wenn man diese Zahl in Bool umwandeln würde wäre das immer True. Und deshalb lande der Code nicht im IF-Block wenn man 'Cinema' wählt (bei den anderen aber schon).

Bei `selectLang` prüftst du ja, korrekter weise, ob ein Wert >= 0 vorliegt. Das tust du bei `selectType `aber nicht.

**Comment by stereodruid** [comment]
Oh Gott, du hast natürlich recht. Hatte total nenn Brett vorm Kopf. 
Im Moment gilt die Bedingung >= 0 nur für selectLang, selectTypes wird alls bool behandelt.

Manchmal sieht man den Wald vor lauter Bäumen nicht :)
Wird korrigiert.
Danke.

**Comment by stereodruid** [comment]
Ist umgesetzt.

**Comment by ghost** [comment]
wunderbar :)

Kommt dann aber wahrscheinlich erst mit 0.4.2 in die Repro oder?

**Comment by stereodruid** [comment]
Ist bereits im Master-Code. Sollte gleich greifen und in der Repo landen. Neue Version ist 0.4.2
